name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build binary
      shell: bash
      run: |
        mkdir -p dist
        CGO_ENABLED=1 go build -o ./dist/marmot .

    # - name: Test
    #   run: go test -v ./...

    - uses: actions/upload-artifact@v3
      with:
        path: dist/marmot
